# Publish to PyPI when pushed to release/latest
# Uses Trusted Publishing (OIDC) - no API token needed

name: Publish to PyPI

on:
  push:
    branches:
      - "release/latest"

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    environment: publish  # Create this environment in GitHub repo settings
    permissions:
      id-token: write  # Required for PyPI Trusted Publishing (OIDC)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Read project version
        id: version
        shell: bash
        run: |
          VERSION=$(python - << 'PY'
          import sys
          sys.path.insert(0, 'src')
          from [PACKAGE_NAME] import __version__
          print(__version__)
          PY
          )
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Install packaging lib
        run: |
          python -m pip install --upgrade pip packaging

      - name: Ensure version not already on PyPI
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "Version to publish: $VERSION"
          python - << 'PY'
          import json, sys, urllib.request
          from packaging.version import Version

          name = '[PACKAGE_NAME]'
          version = '${{ steps.version.outputs.version }}'

          # Normalize PEP 440 version
          try:
              version = str(Version(version))
          except Exception:
              pass

          try:
              with urllib.request.urlopen(f'https://pypi.org/pypi/{name}/json', timeout=10) as r:
                  data = json.load(r)
              exists = version in data.get('releases', {})
          except Exception:
              exists = False

          if exists:
              print(f'Version {version} already exists on PyPI. Bump __version__ first.')
              sys.exit(1)
          else:
              print(f'Version {version} not on PyPI; proceeding.')
          PY

      - name: Build sdist and wheel
        run: |
          pip install build
          python -m build
          echo "Built artifacts:"
          ls -l dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: false
          packages-dir: dist/
