# Python package CI workflow
# Runs tests, linting, type checking, and security scans

name: Python package

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Option A: requirements.txt
          # pip install -r requirements.txt
          # pip install pytest pytest-cov black ruff mypy bandit pip-audit

          # Option B: pyproject.toml with dev extras
          pip install -e ".[dev]" bandit

      - name: Run pytest
        run: |
          pytest -q --cov=[PACKAGE_NAME] --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.python-version == '3.12'
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Format check with Black
        run: |
          black --check --diff src tests

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Type check with mypy (non-blocking)
        run: |
          mypy src
        continue-on-error: true

      - name: Bandit security scan
        run: |
          bandit -r src -x tests/

      - name: Dependency audit with pip-audit (non-blocking)
        run: |
          python -m pip install pip-audit
          pip-audit -s
        continue-on-error: true
